# Generated by Django 5.2.16 on 2026-07-14 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("realty", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntrepreneurProAccess",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("single_report", "Single report"), ("pro", "Pro")],
                        max_length=24,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("usage_limits", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityAnalysis",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_type", models.CharField(max_length=120)),
                ("budget", models.DecimalField(decimal_places=2, max_digits=14)),
                ("business_model", models.CharField(blank=True, max_length=120)),
                ("target_segment", models.CharField(blank=True, max_length=120)),
                ("project_stage", models.CharField(blank=True, max_length=100)),
                ("inputs", models.JSONField(blank=True, default=dict)),
                ("score", models.PositiveSmallIntegerField()),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("strong_fit", "Strong fit"),
                            ("promising", "Promising with checks"),
                            ("review", "Needs further review"),
                            ("not_recommended", "Not recommended now"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "confidence_note",
                    models.CharField(
                        default="Preliminary, based on the inputs available in Istinar.",
                        max_length=255,
                    ),
                ),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("risks", models.JSONField(blank=True, default=list)),
                ("next_steps", models.JSONField(blank=True, default=list)),
                ("analysis_output", models.JSONField(blank=True, default=dict)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_analyses",
                        to="realty.lot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("opportunity_analysis", "Opportunity analysis"),
                            ("lot_comparison", "Lot comparison"),
                        ],
                        max_length=40,
                    ),
                ),
                ("free_limit", models.PositiveIntegerField(default=2)),
                ("used_count", models.PositiveIntegerField(default=0)),
                (
                    "reset_policy",
                    models.CharField(default="lifetime_free_allowance", max_length=40),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "feature"), name="unique_usage_limit"
                    )
                ],
            },
        ),
    ]
