# Generated by Django 5.2.16 on 2026-07-14 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=90, unique=True
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("real_estate_company", "Real estate company"),
                            ("brokerage", "Brokerage office"),
                            ("developer", "Developer"),
                            ("land_owner", "Land owner"),
                        ],
                        default="real_estate_company",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=32)),
                ("website", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("cover_image_url", models.URLField(blank=True)),
                ("primary_color", models.CharField(default="#0B695B", max_length=16)),
                ("accent_color", models.CharField(default="#D8A84C", max_length=16)),
                ("subdomain", models.SlugField(blank=True, max_length=63)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basic",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("approved", "Approved"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_providers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="Development",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=120, unique=True
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "development_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("mixed", "Mixed use"),
                            ("industrial", "Industrial"),
                        ],
                        default="residential",
                        max_length=16,
                    ),
                ),
                ("cover_image_url", models.URLField(blank=True)),
                ("plan_image_url", models.URLField(blank=True)),
                ("amenities", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developments",
                        to="realty.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lot_number", models.CharField(max_length=48)),
                (
                    "polygon",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of normalized x/y vertices.",
                    ),
                ),
                ("area", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("mixed", "Mixed"),
                            ("service", "Service"),
                        ],
                        default="residential",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("negotiation", "Under negotiation"),
                            ("sold", "Sold"),
                            ("unavailable", "Unavailable"),
                            ("hidden", "Hidden"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                ("frontage", models.CharField(blank=True, max_length=100)),
                (
                    "street_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("services", models.JSONField(blank=True, default=list)),
                ("description", models.TextField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_corner", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "development",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="realty.development",
                    ),
                ),
            ],
            options={
                "ordering": ["lot_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("development", "lot_number"),
                        name="unique_lot_number_per_development",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("manager", "Manager"),
                            ("editor", "Editor"),
                            ("analyst", "Analyst"),
                        ],
                        default="editor",
                        max_length=16,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="realty.provider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["provider__name", "user__email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "user"), name="unique_provider_member"
                    )
                ],
            },
        ),
    ]
