# Generated by Django 5.2.16 on 2026-07-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="subdomain",
            field=models.SlugField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
